package org.example.hotelbookingsystembackend.hotel;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Country {
    Afghanistan("Afghanistan", "Afghanistan"),
    Albania("Albania", "Albanien"),
    Algeria("Algeria", "Algeriet"),
    Andorra("Andorra", "Andorra"),
    Angola("Angola", "Angola"),
    Antigua_And_Barbuda("Antigua and Barbuda", "Antigua og Barbuda"),
    Argentina("Argentina", "Argentina"),
    Armenia("Armenia", "Armenien"),
    Australia("Australia", "Australien"),
    Austria("Austria", "Østrig"),
    Azerbaijan("Azerbaijan", "Aserbajdsjan"),
    Bahamas("Bahamas", "Bahamas"),
    Bahrain("Bahrain", "Bahrain"),
    Bangladesh("Bangladesh", "Bangladesh"),
    Barbados("Barbados", "Barbados"),
    Belarus("Belarus", "Hviderusland"),
    Belgium("Belgium", "Belgien"),
    Belize("Belize", "Belize"),
    Benin("Benin", "Benin"),
    Bhutan("Bhutan", "Bhutan"),
    Bolivia("Bolivia", "Bolivia"),
    Bosnia_And_Herzegovina("Bosnia and Herzegovina", "Bosnien-Hercegovina"),
    Botswana("Botswana", "Botswana"),
    Brazil("Brazil", "Brasilien"),
    Brunei("Brunei", "Brunei"),
    Bulgaria("Bulgaria", "Bulgarien"),
    Burkina_Faso("Burkina Faso", "Burkina Faso"),
    Burundi("Burundi", "Burundi"),
    Cabo_Verde("Cape Verde", "Kap Verde"),
    Cambodia("Cambodia", "Cambodja"),
    Cameroon("Cameroon", "Cameroun"),
    Canada("Canada", "Canada"),
    Central_African_Republic("Central African Republic", "Centralafrikanske Republik"),
    Chad("Chad", "Tchad"),
    Chile("Chile", "Chile"),
    China("China", "Kina"),
    Colombia("Colombia", "Colombia"),
    Comoros("Comoros", "Comorerne"),
    Congo_Democratic_Republic("Democratic Republic of the Congo", "Den Demokratiske Republik Congo"),
    Congo_Republic("Republic of the Congo", "Republikken Congo"),
    Costa_Rica("Costa Rica", "Costa Rica"),
    Cote_Divoire("Ivory Coast", "Elfenbenskysten"),
    Croatia("Croatia", "Kroatien"),
    Cuba("Cuba", "Cuba"),
    Cyprus("Cyprus", "Cypern"),
    Czech_Republic("Czech Republic", "Tjekkiet"),
    Denmark("Denmark", "Danmark"),
    Djibouti("Djibouti", "Djibouti"),
    Dominica("Dominica", "Dominica"),
    Dominican_Republic("Dominican Republic", "Den Dominikanske Republik"),
    Ecuador("Ecuador", "Ecuador"),
    Egypt("Egypt", "Egypten"),
    El_Salvador("El Salvador", "El Salvador"),
    Equatorial_Guinea("Equatorial Guinea", "Ækvatorialguinea"),
    Eritrea("Eritrea", "Eritrea"),
    Estonia("Estonia", "Estland"),
    Eswatini("Eswatini", "Eswatini"),
    Ethiopia("Ethiopia", "Etiopien"),
    Fiji("Fiji", "Fiji"),
    Finland("Finland", "Finland"),
    France("France", "Frankrig"),
    Gabon("Gabon", "Gabon"),
    Gambia("Gambia", "Gambia"),
    Georgia("Georgia", "Georgien"),
    Germany("Germany", "Tyskland"),
    Ghana("Ghana", "Ghana"),
    Greece("Greece", "Grækenland"),
    Grenada("Grenada", "Grenada"),
    Guatemala("Guatemala", "Guatemala"),
    Guinea("Guinea", "Guinea"),
    Guinea_Bissau("Guinea-Bissau", "Guinea-Bissau"),
    Guyana("Guyana", "Guyana"),
    Haiti("Haiti", "Haiti"),
    Honduras("Honduras", "Honduras"),
    Hungary("Hungary", "Ungarn"),
    Iceland("Iceland", "Island"),
    India("India", "Indien"),
    Indonesia("Indonesia", "Indonesien"),
    Iran("Iran", "Iran"),
    Iraq("Iraq", "Irak"),
    Ireland("Ireland", "Irland"),
    Israel("Israel", "Israel"),
    Italy("Italy", "Italien"),
    Jamaica("Jamaica", "Jamaica"),
    Japan("Japan", "Japan"),
    Jordan("Jordan", "Jordan"),
    Kazakhstan("Kazakhstan", "Kasakhstan"),
    Kenya("Kenya", "Kenya"),
    Kiribati("Kiribati", "Kiribati"),
    Korea_North("North Korea", "Nordkorea"),
    Korea_South("South Korea", "Sydkorea"),
    Kosovo("Kosovo", "Kosovo"),
    Kuwait("Kuwait", "Kuwait"),
    Kyrgyzstan("Kyrgyzstan", "Kirgisistan"),
    Laos("Laos", "Laos"),
    Latvia("Latvia", "Letland"),
    Lebanon("Lebanon", "Libanon"),
    Lesotho("Lesotho", "Lesotho"),
    Liberia("Liberia", "Liberia"),
    Libya("Libya", "Libyen"),
    Liechtenstein("Liechtenstein", "Liechtenstein"),
    Lithuania("Lithuania", "Litauen"),
    Luxembourg("Luxembourg", "Luxembourg"),
    Madagascar("Madagascar", "Madagaskar"),
    Malawi("Malawi", "Malawi"),
    Malaysia("Malaysia", "Malaysia"),
    Maldives("Maldives", "Maldiverne"),
    Mali("Mali", "Mali"),
    Malta("Malta", "Malta"),
    Marshall_Islands("Marshall Islands", "Marshalløerne"),
    Mauritania("Mauritania", "Mauretanien"),
    Mauritius("Mauritius", "Mauritius"),
    Mexico("Mexico", "Mexico"),
    Micronesia("Micronesia", "Mikronesien"),
    Moldova("Moldova", "Moldova"),
    Monaco("Monaco", "Monaco"),
    Mongolia("Mongolia", "Mongoliet"),
    Montenegro("Montenegro", "Montenegro"),
    Morocco("Morocco", "Marokko"),
    Mozambique("Mozambique", "Mozambique"),
    Myanmar("Myanmar", "Myanmar"),
    Namibia("Namibia", "Namibia"),
    Nauru("Nauru", "Nauru"),
    Nepal("Nepal", "Nepal"),
    Netherlands("Netherlands", "Nederlandene"),
    New_Zealand("New Zealand", "New Zealand"),
    Nicaragua("Nicaragua", "Nicaragua"),
    Niger("Niger", "Niger"),
    Nigeria("Nigeria", "Nigeria"),
    North_Macedonia("North Macedonia", "Nordmakedonien"),
    Norway("Norway", "Norge"),
    Oman("Oman", "Oman"),
    Pakistan("Pakistan", "Pakistan"),
    Palau("Palau", "Palau"),
    Palestine("Palestine", "Palæstina"),
    Panama("Panama", "Panama"),
    Papua_New_Guinea("Papua New Guinea", "Papua Ny Guinea"),
    Paraguay("Paraguay", "Paraguay"),
    Peru("Peru", "Peru"),
    Philippines("Philippines", "Filippinerne"),
    Poland("Poland", "Polen"),
    Portugal("Portugal", "Portugal"),
    Qatar("Qatar", "Qatar"),
    Romania("Romania", "Rumænien"),
    Russia("Russia", "Rusland"),
    Rwanda("Rwanda", "Rwanda"),
    Saint_Kitts_And_Nevis("Saint Kitts and Nevis", "Saint Kitts og Nevis"),
    Saint_Lucia("Saint Lucia", "Saint Lucia"),
    Saint_Vincent_And_The_Grenadines("Saint Vincent and the Grenadines", "Saint Vincent og Grenadinerne"),
    Samoa("Samoa", "Samoa"),
    San_Marino("San Marino", "San Marino"),
    Sao_Tome_And_Principe("São Tomé and Príncipe", "São Tomé og Príncipe"),
    Saudi_Arabia("Saudi Arabia", "Saudi-Arabien"),
    Senegal("Senegal", "Senegal"),
    Serbia("Serbia", "Serbien"),
    Seychelles("Seychelles", "Seychellerne"),
    Sierra_Leone("Sierra Leone", "Sierra Leone"),
    Singapore("Singapore", "Singapore"),
    Slovakia("Slovakia", "Slovakiet"),
    Slovenia("Slovenia", "Slovenien"),
    Solomon_Islands("Solomon Islands", "Salomonøerne"),
    Somalia("Somalia", "Somalia"),
    South_Africa("South Africa", "Sydafrika"),
    South_Sudan("South Sudan", "Sydsudan"),
    Spain("Spain", "Spanien"),
    Sri_Lanka("Sri Lanka", "Sri Lanka"),
    Sudan("Sudan", "Sudan"),
    Suriname("Suriname", "Surinam"),
    Sweden("Sweden", "Sverige"),
    Switzerland("Switzerland", "Schweiz"),
    Syria("Syria", "Syrien"),
    Taiwan("Taiwan", "Taiwan"),
    Tajikistan("Tajikistan", "Tadsjikistan"),
    Tanzania("Tanzania", "Tanzania"),
    Thailand("Thailand", "Thailand"),
    Timor_Leste("Timor-Leste", "Østtimor"),
    Togo("Togo", "Togo"),
    Tonga("Tonga", "Tonga"),
    Trinidad_And_Tobago("Trinidad and Tobago", "Trinidad og Tobago"),
    Tunisia("Tunisia", "Tunesien"),
    Turkey("Turkey", "Tyrkiet"),
    Turkmenistan("Turkmenistan", "Turkmenistan"),
    Tuvalu("Tuvalu", "Tuvalu"),
    Uganda("Uganda", "Uganda"),
    Ukraine("Ukraine", "Ukraine"),
    United_Arab_Emirates("United Arab Emirates", "Forenede Arabiske Emirater"),
    United_Kingdom("United Kingdom", "Storbritannien"),
    United_States("United States", "USA"),
    Uruguay("Uruguay", "Uruguay"),
    Uzbekistan("Uzbekistan", "Usbekistan"),
    Vanuatu("Vanuatu", "Vanuatu"),
    Vatican_City("Vatican City", "Vatikanstaten"),
    Venezuela("Venezuela", "Venezuela"),
    Vietnam("Vietnam", "Vietnam"),
    Yemen("Yemen", "Yemen"),
    Zambia("Zambia", "Zambia"),
    Zimbabwe("Zimbabwe", "Zimbabwe");

    private final String englishName;
    private final String danishName;

}
